# Generated by Django 3.2.8 on 2021-10-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0005_purchases_date_purchase_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
