# Generated by Django 3.2.8 on 2021-10-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0006_purchases_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='datepurchase',
            name='view',
            field=models.CharField(default='notyet', max_length=255),
        ),
    ]
