# Generated by Django 3.2.8 on 2021-10-29 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0007_datepurchase_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='datepurchase',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
