# Generated by Django 3.2.8 on 2021-10-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0008_datepurchase_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='datepurchase',
            name='address',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datepurchase',
            name='country',
            field=models.CharField(default='dfdf', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datepurchase',
            name='countrycode',
            field=models.CharField(default='dfdfddf', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datepurchase',
            name='postcode',
            field=models.CharField(default='dsfvsfvfs', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datepurchase',
            name='state',
            field=models.CharField(default='dfvsfv', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datepurchase',
            name='tell',
            field=models.CharField(default='dfvdfvdfv', max_length=255),
            preserve_default=False,
        ),
    ]
