# Generated by Django 3.2.8 on 2021-10-31 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0011_auto_20211101_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='date_purchase_pk',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='product_pk',
            field=models.IntegerField(),
        ),
    ]
