# Generated by Django 3.2.8 on 2021-10-31 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0013_alter_purchases_date_purchase_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='date_purchase_pk',
            field=models.DateField(),
        ),
    ]
