# Generated by Django 3.2.8 on 2021-10-31 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0014_alter_purchases_date_purchase_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='datepurchase',
            name='unique_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
