# Generated by Django 3.2.8 on 2021-10-31 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0015_datepurchase_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datepurchase',
            name='unique_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='date_purchase_pk',
            field=models.IntegerField(),
        ),
    ]
