# Generated by Django 3.2.8 on 2021-11-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0016_auto_20211101_0516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Msgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
