# Generated by Django 3.2.8 on 2021-11-03 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0017_msgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='msgs',
            name='status',
            field=models.CharField(default='unread', max_length=20),
        ),
    ]
