# Generated by Django 3.2.8 on 2021-10-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniadmin', '0005_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='video',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
